### Session 13 Assignment 2

#### In this assignment students will build the random forest model after normalizing the variable to house pricing from boston data set.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import datasets

##### Loading a dataset from pandas dataset and transforming into a pandas dataframe

In [3]:
boston = datasets.load_boston()
features = pd.DataFrame(boston.data, columns=boston.feature_names)
targets = boston.target
features.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [13]:
# Checking Whether "targets" array have any NAN
np.isnan(targets).any()

False

In [5]:
# DATA Preprocessing.
# Replacing NAN values with median
features.fillna(features.median,inplace=True)

In [14]:
# Creating input in X and Y axis
X = features.iloc[:,:-1].values
Y = targets
print("X-DATASET:\n",X)
print("Y-DATASET:\n",Y)

X-DATASET:
 [[6.3200e-03 1.8000e+01 2.3100e+00 ... 2.9600e+02 1.5300e+01 3.9690e+02]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 2.4200e+02 1.7800e+01 3.9690e+02]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 2.4200e+02 1.7800e+01 3.9283e+02]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.7300e+02 2.1000e+01 3.9690e+02]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.7300e+02 2.1000e+01 3.9345e+02]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.7300e+02 2.1000e+01 3.9690e+02]]
Y-DATASET:
 [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1

In [15]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.10,random_state=42,shuffle=True)
print("X-TRAINING DATA:\n",X_train)
print("X-TEST DATA:\n",X_test)
print("Y-TRAINING DATA:\n",y_train)
print("Y-TEST DATA:\n",y_test)

X-TRAINING DATA:
 [[3.70500e-02 2.00000e+01 3.33000e+00 ... 2.16000e+02 1.49000e+01
  3.92230e+02]
 [1.23247e+00 0.00000e+00 8.14000e+00 ... 3.07000e+02 2.10000e+01
  3.96900e+02]
 [1.14320e-01 0.00000e+00 8.56000e+00 ... 3.84000e+02 2.09000e+01
  3.95580e+02]
 ...
 [1.50100e-02 8.00000e+01 2.01000e+00 ... 2.80000e+02 1.70000e+01
  3.90940e+02]
 [1.11604e+01 0.00000e+00 1.81000e+01 ... 6.66000e+02 2.02000e+01
  1.09850e+02]
 [2.28760e-01 0.00000e+00 8.56000e+00 ... 3.84000e+02 2.09000e+01
  7.08000e+01]]
X-TEST DATA:
 [[9.17800e-02 0.00000e+00 4.05000e+00 0.00000e+00 5.10000e-01 6.41600e+00
  8.41000e+01 2.64630e+00 5.00000e+00 2.96000e+02 1.66000e+01 3.95500e+02]
 [5.64400e-02 4.00000e+01 6.41000e+00 1.00000e+00 4.47000e-01 6.75800e+00
  3.29000e+01 4.07760e+00 4.00000e+00 2.54000e+02 1.76000e+01 3.96900e+02]
 [1.05740e-01 0.00000e+00 2.77400e+01 0.00000e+00 6.09000e-01 5.98300e+00
  9.88000e+01 1.86810e+00 4.00000e+00 7.11000e+02 2.01000e+01 3.90110e+02]
 [9.16400e-02 0.00000e+00 1.0

In [16]:
# Feature Scaling X data set
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print("X-TRAINING DATA AFTER FEATURE SCALING:\n",X_train)
print("X-TEST DATA AFTER FEATURE SCALING:\n",X_test)

X-TRAINING DATA AFTER FEATURE SCALING:
 [[-0.41694218  0.34451337 -1.11796605 ... -1.14455458 -1.60174615
   0.3982937 ]
 [-0.2800016  -0.49972297 -0.42106823 ... -0.60186597  1.1755678
   0.44841978]
 [-0.40809056 -0.49972297 -0.36021645 ... -0.14266793  1.13003807
   0.43425138]
 ...
 [-0.41946696  2.87722238 -1.30921451 ... -0.76288347 -0.64562168
   0.3844473 ]
 [ 0.85728607 -0.49972297  1.02198836 ...  1.53907038  0.81132991
  -2.632671  ]
 [-0.39498096 -0.49972297 -0.36021645 ... -0.14266793  1.13003807
  -3.05181957]]
X-TEST DATA AFTER FEATURE SCALING:
 [[-4.10672618e-01 -4.99722970e-01 -1.01364870e+00 -2.70394541e-01
  -3.85566962e-01  1.64534725e-01  5.62730959e-01 -5.44939832e-01
  -5.23106266e-01 -6.67465696e-01 -8.27740625e-01  4.33392691e-01]
 [-4.14720969e-01  1.18874970e+00 -6.71719630e-01  3.69829952e+00
  -9.25028733e-01  6.47241472e-01 -1.25536493e+00  1.15973944e-01
  -6.38366969e-01 -9.17937359e-01 -3.72443255e-01  4.48419785e-01]
 [-4.09073439e-01 -4.99722970e-01  

In [17]:
# RANDOM FOREST Training / model fitting to the training data set
model = RandomForestRegressor(random_state=0, n_estimators=100)
model.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [18]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred

array([22.71 , 29.283, 14.899, 22.182, 20.443, 21.763, 19.62 , 17.381,
       19.835, 20.085, 19.877, 19.861,  8.579, 22.209, 19.546, 26.389,
       18.349,  8.815, 47.285, 14.562, 26.329, 24.326, 15.164, 23.634,
       14.247, 14.655, 21.192, 13.282, 19.943, 20.897, 19.955, 23.624,
       27.906, 17.724, 17.976, 16.579, 33.658, 19.254, 21.607, 24.601,
       19.219, 30.328, 47.472, 19.72 , 22.605, 13.441, 15.269, 25.007,
       19.822, 26.646, 19.8  ])

In [20]:
model_score = model.score(X_train,y_train)
print("Co-Efficient of determination R^2 of the prediction.:",model_score)
print("Mean squared error: %.2f"% mean_squared_error(y_test, y_pred))
print('Test Variance score: %.2f' % r2_score(y_test, y_pred))

Co-Efficient of determination R^2 of the prediction.: 0.9676762557233288
Mean squared error: 7.32
Test Variance score: 0.88


We can see that our R^2 score and MSE are both very good. This means that we have found a
best fitting model to predict the median price value of a house. 